# Generated by sila2.code_generator; sila2.__version__: 0.10.4

from typing import Optional
from uuid import UUID

from sila2.server import SilaServer

from .feature_implementations.agarcontroller_impl import AgarControllerImpl
from .generated.agarcontroller import AgarControllerFeature


class Server(SilaServer):
    def __init__(self, server_uuid: Optional[UUID] = None):
        # TODO: fill in your server information
        super().__init__(
            server_name="AgarStation",
            server_type="AgarStation",
            server_version="0.1",
            server_description="Agar Station Sila-2 Server",
            server_vendor_url="https://gitlab.com/SiLA2/sila_python",
            server_uuid=server_uuid,
        )

        self.agarcontroller = AgarControllerImpl(self)
        self.set_feature_implementation(AgarControllerFeature, self.agarcontroller)
